# Generated by Django 5.0.7 on 2026-06-25 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_pedido', models.CharField(choices=[('APP', 'App'), ('TOTEM', 'Totem'), ('BALCAO', 'Balcão'), ('PICKUP', 'Pickup'), ('WEB', 'Web')], max_length=20)),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGO', 'Pago'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado'), ('PAGAMENTO_RECUSADO', 'Pagamento recusado')], default='AGUARDANDO_PAGAMENTO', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
