# Generated by Django 5.0.7 on 2026-06-25 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('MOCK', 'Mock'), ('PIX', 'Pix simulado'), ('CARTAO', 'Cartão simulado')], default='MOCK', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('transacao_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('payload_retorno', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
